### PR TITLE
Support flake8 v6

### PR DESCRIPTION
**Pull request by jabbera**
No core code changes needed. Unit tests had to be updated to support new parameter.

### CODE REVIEW

**Comment by jabbera** [comment]
Note: Must merge https://github.com/Takishima/flake8-secure-coding-standard/pull/47 first to fix CI

**Review by Takishima — APPROVED** [review]
Only missing a modification in the CHANGELOG file to explain the changes.

**Comment by Takishima** [comment]
And thank you @jabbera for submitting the changes

**Comment by jabbera** [comment]
All set with the changelog.

**Comment by Takishima** [comment]
I took the liberty to make a few tweaks. Once the tests pass, I will merge this and then create a new release.

**Pull request merged**
